### ISSUE TITLE
Implement trial configuration and running

### ISSUE THREAD

**Issue by blakeNaccarato** [blakeNaccarato/boilerdata#12]
The master config may be best put in the `boilerdata` package itself, or else near the OriginLab project. String variables in the subfolders could be used to index into common configs like sample dimensions and such.

# Tasks

After recent thinking, and figuring out the interaction between Pydantic and Enums, these are the properties of a well-structured `trials.toml` and its features:

- [x] The top-level key is `trials` and contains a list of `Trial`
- [x] `Trial` has fields name (which is usually just the date), rod, upper, joint, sample, sample type, good.
- [x] rod, upper, sample: Used to pull stuff from `boilerdata.toml`
- [x] joint: No current use aside from grouping, but could be used later

Trials will be a standard Python list so they can be iterated over etc. Additionally, grouping the trials list by any of its keys should be supported.

The thing about restricting choices on trials is that actual Enum code generation is needed. There is no programmatic way to define Enum members aside from in the class variables.

So the rod, upper, sample, and joint items will be required and also part of generated Enums.

- [x] ~update_enum function which puts arbitrarily named enums in a file for later use in models. CLI~

The updating of `trials.toml` to include new files is made by the following.

- [ ] load current file into fully-fledged model
- [ ] look for new trials in base folder
- [ ] generate records based on under-specified model
- [x] check if Pydantic requires specifying fields when Field(...) is specified. If so, then define a different base model with only few properties
- [ ] append new records to full records from file, dump back to file

The library code built off of trials should be
- [x] Get runs for a given trial

The run() code should be run for each trial

- [x] Get folder of trials from base config
- [x] Get runs for a trial and process them
- [x] Output to combined CSV.

**Comment by blakeNaccarato** [comment]
After recent thinking, and figuring out the interaction between Pydantic and Enums, these are the properties of a well-structured `trials.toml` and its features:

- [ ] The top-level key is `trials` and contains a list of `Trial`
- [ ] `Trial` has fields name (which is usually just the date), rod, upper, joint, sample, good.
- [ ] rod, upper, sample: Used to pull stuff from `boilerdata.toml`
- [ ] joint: No current use aside from grouping, but could be used later

The thing about restricting choices on trials is that actual Enum code generation is needed. There is no programmatic way to define Enum members aside from in the class variables.

So the rod, upper, sample, and joint items will be required and also part of generated Enums.

- [ ] update_enum function which puts arbitrarily named enums in a file for later use in models. CLI

The updating of `trials.toml` to include new files is made by the following

- [ ] load current file into fully-fledged model
- [ ] look for new trials in base folder
- [ ] generate records based on under-specified model
- [ ] check if Pydantic requires specifying fields when Field(...) is specified. If so, then define a different base model with only few properties
- [ ] append new records to full records from file, dump back to file

The run() code should be run for each trial

- [ ] Get folder of trials from base config
- [ ] Get

**Comment by blakeNaccarato** [comment]
Going to keep tracking this in `main`.

**Comment by blakeNaccarato** [comment]
Just need to implement extending `trials.yaml` with new trials. But it's not high priority since they can be added manually easily enough.

**Comment by blakeNaccarato** [comment]
I have a "new" flag in each trial. I can also put a "number of thermocouples" flag that defaults to "5", and automatically map TC's to x-positions in validation or some `__init__()`. This would generalize that calculation, and a forking path could be placed in the pipeline where surface temperature is just prescribed instead of regressed, for example.

**Comment by blakeNaccarato** [comment]
This is done now with the help of DVC
