### ISSUE TITLE
Change columns model to a list. Implement convenience properties for source, meta, index, etc.

### ISSUE THREAD

**Issue by blakeNaccarato** [blakeNaccarato/boilerdata#50]
## First

- [x] Change cols model to a list. Name it `all_cols`?

## Next

- [x] Project adopts entire Columns model, not just its `cols`/`all_cols` attribute

## Implement convenience sets for unions of columns

- [x] index
- [x] cols
- [x] meta

## Finally

- [x] Migrate dtype getter into model
